### ISSUE TITLE
Database Errors with version 1.1.0

### ISSUE THREAD

**Issue by bjko** [kaliop-uk/ezworkflowenginebundle#10]
We have some strange behavior after upgrading to version 1.1.0. We are not able to publish any content, even if the is no yml file in the defintion folder.

the comand line tools thrwos this error:
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to Kaliop\eZWorkflowEngineBundle\Core\StorageHandler\Database\Workflow::__construct() must be an instance o
  f Kaliop\eZWorkflowEngineBundle\Core\StorageHandler\Database\DatabaseHandler, instance of eZPublishCorePersistenceDoctrineConnectionHandl
  er_0000000016addadb00000000796a17a53e15d0cd5188c906535c81cc78ea2558 given, called in /var/www//htdocs/app/cache/prod/appProdProjectContainer.php on line 4237

Seems there is some trouble withe the changes in database constructor. 
We are ussing ezpublish-kernel 6.13.2

**Comment by gggeek** [comment]
Sorry :-( Will look into that asap. Definitely time to introduce Travis testing :-)

**Comment by gggeek** [comment]
Should be fixed in 1.1.1. (was missing a use statement. bad copypasta!)

**Comment by bjko** [comment]
works! Thank you
