### ISSUE TITLE
Error with ezpublish-kernel 7.1

### ISSUE THREAD

**Issue by bjko** [kaliop-uk/ezworkflowenginebundle#11]
Error while cleaning the prod cache in ezpublish-kernel 7.1
In AbstractRecursivePass.php line 158:

Invalid service "ez_workflowengine_bundle.workflow_service.facade": method "Kaliop\eZWorkflowEngineBundle\Core\WorkflowServiceFacade::addDefinitionParser()" does not exist.

While referencing functions addDefinitionParser and addExecutor from ezmigrationbundle/Core/MigrationService.php it works fine

**Comment by gggeek** [comment]
Tentative fix in 7f30c227637f364d1451f91beb5ed3e333fe4a54 - could you please test it ?

**Comment by bjko** [comment]
Sorry, it does not work. I still get the error

In AbstractRecursivePass.php line 158:

  Invalid service "ez_workflowengine_bundle.workflow_service.facade": method
  "Kaliop\eZWorkflowEngineBundle\Core\WorkflowServiceFacade::addDefinitionPar
  ser()" does not exist.


Script eZ\Bundle\EzPublishCoreBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception


  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  In AbstractRecursivePass.php line 158:

    Invalid service "ez_workflowengine_bundle.workflow_service.facade": method
    "Kaliop\eZWorkflowEngineBundle\Core\WorkflowServiceFacade::addDefinitionPar
    ser()" does not exist.

**Comment by gggeek** [comment]
Doh. That's what happens when you try to fix stuff late and night even though you are tired.
The correct fix should (hopefully) be in ea083c14aa7f5ce3726554c475ccd689f4fb2847

**Comment by bjko** [comment]
No, this does not fix it, still the same error

**Comment by bjko** [comment]
Sorry, different error massage

 Invalid service "ez_workflowengine_bundle.workflow_service.facade": method "Kaliop\eZWorkflowEngineBundle\Core\WorkflowServiceFacade::add
  Executor()" does not exist.

Another methode is missing.

**Comment by gggeek** [comment]
3rd time a charm ? 37394a2d994f47da1a3181c1946e45752684feb0

**Comment by bjko** [comment]
This seems to work. The error messages are gone. But I am running in the next error while running the command line scripts (status, debug, cleanup, resume), e.g.

 php bin/console kaliop:workflows:debug --env=prod --siteaccess=demo
10:21:43 ERROR     [console] Error thrown while running command "kaliop:workflows:debug --env=prod --siteaccess=demo". Message: "The helper "table" is not defined." ["exception" => Symfony\Component\Console\Exception\InvalidArgumentException { …},"command" => "kaliop:workflows:debug --env=prod --siteaccess=mandant01","message" => "The helper "table" is not defined."] []

  The helper "table" is not defined

I found this in the symfony docu:
The table helper has been deprecated in symfony 2.5 and removed in 3.0.
http://symfony.com/doc/current/components/console/helpers/tablehelper.html

**Comment by gggeek** [comment]
Ok, this tail-chasing-game is getting a bit too long to be fun any more. I will install eZPlatform v2 with corresponding Sf version and test by myself...

**Comment by gggeek** [comment]
ps: table fix: fe785620569933c779545b5e959d0b3952f1263e

**Comment by bjko** [comment]
This solved the issues. After doing a short test the bundle is working fine:-) Thank you!
